# Generated by Django 4.2.3 on 2023-07-23 19:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LadderDomainHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="目標領域分類ヘッダー名称")),
            ],
        ),
        migrations.CreateModel(
            name="LadderSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "target_list",
                    models.JSONField(
                        help_text="ラダーの設定目標リストを json で定義します", verbose_name="目標リスト"
                    ),
                ),
                (
                    "point_legend",
                    models.JSONField(
                        blank=True,
                        help_text="評価項目の点数の凡例を定義します",
                        null=True,
                        verbose_name="点数の凡例",
                    ),
                ),
                (
                    "max_point",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="評価点数の最大値",
                    ),
                ),
                (
                    "domain_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ladder.ladderdomainhead",
                        verbose_name="目標領域分類ヘッダー",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LadderDomainClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth", models.IntegerField(editable=False)),
                ("queue", models.PositiveIntegerField(editable=False)),
                ("title", models.CharField(max_length=200, verbose_name="目標領域分類名")),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="ladder.ladderdomainhead",
                        verbose_name="目標領域分類ヘッダー",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LadderCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="評価項目文")),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_set",
                        to="ladder.laddersheet",
                        verbose_name="ラダーシート",
                    ),
                ),
                (
                    "target_item",
                    models.ForeignKey(
                        help_text="項目がどの領域分類に属するかを表します",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ladder.ladderdomainclass",
                        verbose_name="目標領域分類",
                    ),
                ),
            ],
        ),
    ]
