# Generated by Django 4.2.3 on 2023-07-25 01:43

from django.db import migrations, models

import ladder.models


class Migration(migrations.Migration):

    dependencies = [
        ("ladder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laddersheet",
            name="target_list",
        ),
        migrations.AddField(
            model_name="laddersheet",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="運用終了日"),
        ),
        migrations.AddField(
            model_name="laddersheet",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="運用開始日"),
        ),
        migrations.AddField(
            model_name="laddersheet",
            name="targets",
            field=models.JSONField(
                default='{"targets":[]}',
                help_text="ラダーの設定目標リストを json で定義します",
                validators=[ladder.models.validate_target_list_format],
                verbose_name="目標リスト",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="laddersheet",
            name="point_legend",
            field=models.JSONField(
                blank=True,
                help_text="評価項目の点数の凡例を定義します",
                null=True,
                validators=[ladder.models.validate_point_legend_format],
                verbose_name="点数の凡例",
            ),
        ),
    ]
