# Generated by Django 4.2.3 on 2023-07-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ladder", "0002_remove_laddersheet_target_list_laddersheet_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laddercriterion",
            name="text",
            field=models.CharField(max_length=200, verbose_name="評価基準項目文"),
        ),
    ]
