version: '3'
services:
  django:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        gh_token: ${GH_TOKEN}
    image: py11-django
    container_name: ${PROJECT_NAME}-django
    volumes:
      - ./src:/home/appuser/app
    env_file:
      - .env
    ports:
      - ${DJANGO_CONTAINER_PORT}:8000
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_CONTAINER_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3-alpine3.18
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    container_name: ${PROJECT_NAME}-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    ports:
      - ${DB_CONTAINER_PORT}:5432
