# Generated by Django 4.2.3 on 2023-07-25 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ladder_evaluations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ladder", "0003_alter_laddercriterion_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新日時"),
                ),
                ("level", models.IntegerField(verbose_name="レベル")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONGOING", "実施中"),
                            ("CANCELED", "キャンセル"),
                            ("FINISHED", "評価済"),
                        ],
                        default="ONGOING",
                        max_length=15,
                        verbose_name="評価状況",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ladder.laddersheet",
                        verbose_name="ラダーシート",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申請ユーザー",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SummaryAdditionalEvaluationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新日時"),
                ),
                (
                    "result",
                    models.IntegerField(
                        choices=[(0, "Ng"), (1, "Ok")],
                        default=0,
                        help_text="1: 可, 0: 保留",
                        verbose_name="評価結果",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="総括評価日"
                    ),
                ),
                ("fixed", models.BooleanField(default=False, verbose_name="確定済みフラグ")),
                (
                    "evaluation_points",
                    models.JSONField(
                        default=ladder_evaluations.models._evaluation_points_default_value,
                        help_text="評価内容を json で記録します",
                        verbose_name="評価内容",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="コメント"),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ladder_evaluations.evaluationapplication",
                        verbose_name="評価申請",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="評価責任者",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新日時"),
                ),
                (
                    "evaluator_type",
                    models.CharField(
                        choices=[
                            ("SELF", "自己評価"),
                            ("COWORKER", "同僚評価"),
                            ("HEAD", "上長評価"),
                        ],
                        max_length=15,
                        verbose_name="評価者区分",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="評価日"
                    ),
                ),
                ("fixed", models.BooleanField(default=False, verbose_name="確定済みフラグ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONGOING", "ongoing"),
                            ("CANCELED", "canceled"),
                            ("FINISHED", "finished"),
                        ],
                        default="ONGOING",
                        max_length=15,
                        verbose_name="評価状況",
                    ),
                ),
                (
                    "evaluation_points",
                    models.JSONField(
                        default=ladder_evaluations.models._evaluation_points_default_value,
                        help_text="評価点を json で記録します",
                        verbose_name="評価点情報",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="評価者",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
