# Generated by Django 4.2.3 on 2023-07-26 05:46

from django.db import migrations, models

import ladder_evaluations.models


class Migration(migrations.Migration):

    dependencies = [
        ("ladder_evaluations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="summaryadditionalevaluationitem",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="status",
        ),
        migrations.AddField(
            model_name="evaluationapplication",
            name="result",
            field=models.IntegerField(
                choices=[(0, "Ng"), (1, "Ok")],
                default=None,
                editable=False,
                help_text="評価総括が記録されたときにその結果が反映されます。(1: 可, 0: 保留)",
                null=True,
                verbose_name="評価結果",
            ),
        ),
        migrations.AddField(
            model_name="summaryadditionalevaluationitem",
            name="order",
            field=models.IntegerField(default=100000, verbose_name="ソート順"),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="evaluation_points",
            field=models.JSONField(
                default=ladder_evaluations.models._evaluation_points_default_value,
                help_text="各評価項目の評価点を json で記録します",
                verbose_name="評価点情報",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationapplication",
            name="level",
            field=models.IntegerField(editable=False, verbose_name="レベル"),
        ),
    ]
